// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiProductsByIdData, DeleteApiProductsByIdResponses, DeleteApiStoresByIdData, DeleteApiStoresByIdResponses, GetApiDashboardMetricsData, GetApiDashboardMetricsResponses, GetApiProductsByIdData, GetApiProductsByIdResponses, GetApiProductsData, GetApiProductsResponses, GetApiStoresByIdData, GetApiStoresByIdResponses, GetApiStoresData, GetApiStoresResponses, GetHealthData, GetHealthResponses, PatchApiProductsByIdData, PatchApiProductsByIdResponses, PatchApiStoresByIdData, PatchApiStoresByIdResponses, PostApiProductsData, PostApiProductsResponses, PostApiStoresData, PostApiStoresResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

export const getApiDashboardMetrics = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardMetricsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardMetricsResponses, unknown, ThrowOnError>({ url: '/api/dashboard/metrics', ...options });

export const getApiStores = <ThrowOnError extends boolean = false>(options?: Options<GetApiStoresData, ThrowOnError>) => (options?.client ?? client).get<GetApiStoresResponses, unknown, ThrowOnError>({ url: '/api/stores', ...options });

export const postApiStores = <ThrowOnError extends boolean = false>(options: Options<PostApiStoresData, ThrowOnError>) => (options.client ?? client).post<PostApiStoresResponses, unknown, ThrowOnError>({
    url: '/api/stores',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiStoresById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiStoresByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiStoresByIdResponses, unknown, ThrowOnError>({ url: '/api/stores/{id}', ...options });

export const getApiStoresById = <ThrowOnError extends boolean = false>(options: Options<GetApiStoresByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiStoresByIdResponses, unknown, ThrowOnError>({ url: '/api/stores/{id}', ...options });

export const patchApiStoresById = <ThrowOnError extends boolean = false>(options: Options<PatchApiStoresByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiStoresByIdResponses, unknown, ThrowOnError>({
    url: '/api/stores/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiProducts = <ThrowOnError extends boolean = false>(options?: Options<GetApiProductsData, ThrowOnError>) => (options?.client ?? client).get<GetApiProductsResponses, unknown, ThrowOnError>({ url: '/api/products', ...options });

export const postApiProducts = <ThrowOnError extends boolean = false>(options: Options<PostApiProductsData, ThrowOnError>) => (options.client ?? client).post<PostApiProductsResponses, unknown, ThrowOnError>({
    url: '/api/products',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiProductsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiProductsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiProductsByIdResponses, unknown, ThrowOnError>({ url: '/api/products/{id}', ...options });

export const getApiProductsById = <ThrowOnError extends boolean = false>(options: Options<GetApiProductsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiProductsByIdResponses, unknown, ThrowOnError>({ url: '/api/products/{id}', ...options });

export const patchApiProductsById = <ThrowOnError extends boolean = false>(options: Options<PatchApiProductsByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiProductsByIdResponses, unknown, ThrowOnError>({
    url: '/api/products/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
