// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiDashboardMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/metrics';
};

export type GetApiDashboardMetricsResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            totalStores: number;
            activeStores: number;
            totalProducts: number;
            inventoryValue: number;
            lowStockCount: number;
            outOfStockCount: number;
            categoryCounts: {
                [key: string]: number;
            };
            lowStockProducts: Array<{
                id: number;
                name: string;
                sku: string;
                quantity: number;
                minStock: number;
                status: string;
                storeName: string;
            }>;
        };
    };
};

export type GetApiDashboardMetricsResponse = GetApiDashboardMetricsResponses[keyof GetApiDashboardMetricsResponses];

export type GetApiStoresData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        status?: 'active' | 'inactive';
        /**
         * Format: field,direction (e.g. name,asc)
         */
        sort?: string;
        page?: number;
        limit?: number;
    };
    url: '/api/stores';
};

export type GetApiStoresResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<{
            id: number;
            name: string;
            location: string;
            manager: string;
            status: 'active' | 'inactive';
            createdAt: string;
            updatedAt: string;
        }>;
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
        links: {
            self: string;
            first: string;
            prev: string | null;
            next: string | null;
            last: string;
        };
    };
};

export type GetApiStoresResponse = GetApiStoresResponses[keyof GetApiStoresResponses];

export type PostApiStoresData = {
    body: {
        name: string;
        location: string;
        manager: string;
        status?: 'active' | 'inactive';
    };
    path?: never;
    query?: never;
    url: '/api/stores';
};

export type PostApiStoresResponses = {
    /**
     * Default Response
     */
    201: {
        data: {
            id: number;
            name: string;
            location: string;
            manager: string;
            status: 'active' | 'inactive';
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PostApiStoresResponse = PostApiStoresResponses[keyof PostApiStoresResponses];

export type DeleteApiStoresByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stores/{id}';
};

export type DeleteApiStoresByIdResponses = {
    /**
     * No content
     */
    204: void;
};

export type DeleteApiStoresByIdResponse = DeleteApiStoresByIdResponses[keyof DeleteApiStoresByIdResponses];

export type GetApiStoresByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stores/{id}';
};

export type GetApiStoresByIdResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: number;
            name: string;
            location: string;
            manager: string;
            status: 'active' | 'inactive';
            createdAt: string;
            updatedAt: string;
            productSummary: {
                total: number;
                lowStock: number;
                outOfStock: number;
            };
        };
    };
};

export type GetApiStoresByIdResponse = GetApiStoresByIdResponses[keyof GetApiStoresByIdResponses];

export type PatchApiStoresByIdData = {
    body: {
        name?: string;
        location?: string;
        manager?: string;
        status?: 'active' | 'inactive';
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stores/{id}';
};

export type PatchApiStoresByIdResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: number;
            name: string;
            location: string;
            manager: string;
            status: 'active' | 'inactive';
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PatchApiStoresByIdResponse = PatchApiStoresByIdResponses[keyof PatchApiStoresByIdResponses];

export type GetApiProductsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        category?: 'electronics' | 'clothing' | 'food' | 'furniture' | 'tools' | 'other';
        status?: 'in_stock' | 'low_stock' | 'out_of_stock';
        storeId?: number;
        minPrice?: number;
        maxPrice?: number;
        /**
         * Format: field,direction (e.g. price,desc)
         */
        sort?: string;
        page?: number;
        limit?: number;
    };
    url: '/api/products';
};

export type GetApiProductsResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<{
            id: number;
            name: string;
            sku: string;
            category: 'electronics' | 'clothing' | 'food' | 'furniture' | 'tools' | 'other';
            price: number;
            quantity: number;
            minStock: number;
            status: 'in_stock' | 'low_stock' | 'out_of_stock';
            storeId: number;
            storeName: string;
            createdAt: string;
            updatedAt: string;
        }>;
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
        links: {
            self: string;
            first: string;
            prev: string | null;
            next: string | null;
            last: string;
        };
    };
};

export type GetApiProductsResponse = GetApiProductsResponses[keyof GetApiProductsResponses];

export type PostApiProductsData = {
    body: {
        name: string;
        sku: string;
        category: 'electronics' | 'clothing' | 'food' | 'furniture' | 'tools' | 'other';
        price: number;
        quantity?: number;
        minStock?: number;
        storeId: number;
    };
    path?: never;
    query?: never;
    url: '/api/products';
};

export type PostApiProductsResponses = {
    /**
     * Default Response
     */
    201: {
        data: {
            id: number;
            name: string;
            sku: string;
            category: 'electronics' | 'clothing' | 'food' | 'furniture' | 'tools' | 'other';
            price: number;
            quantity: number;
            minStock: number;
            status: 'in_stock' | 'low_stock' | 'out_of_stock';
            storeId: number;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PostApiProductsResponse = PostApiProductsResponses[keyof PostApiProductsResponses];

export type DeleteApiProductsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type DeleteApiProductsByIdResponses = {
    /**
     * No content
     */
    204: void;
};

export type DeleteApiProductsByIdResponse = DeleteApiProductsByIdResponses[keyof DeleteApiProductsByIdResponses];

export type GetApiProductsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type GetApiProductsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: number;
            name: string;
            sku: string;
            category: 'electronics' | 'clothing' | 'food' | 'furniture' | 'tools' | 'other';
            price: number;
            quantity: number;
            minStock: number;
            status: 'in_stock' | 'low_stock' | 'out_of_stock';
            storeId: number;
            storeName: string;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type GetApiProductsByIdResponse = GetApiProductsByIdResponses[keyof GetApiProductsByIdResponses];

export type PatchApiProductsByIdData = {
    body: {
        name?: string;
        sku?: string;
        category?: 'electronics' | 'clothing' | 'food' | 'furniture' | 'tools' | 'other';
        price?: number;
        quantity?: number;
        minStock?: number;
        storeId?: number;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type PatchApiProductsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: number;
            name: string;
            sku: string;
            category: 'electronics' | 'clothing' | 'food' | 'furniture' | 'tools' | 'other';
            price: number;
            quantity: number;
            minStock: number;
            status: 'in_stock' | 'low_stock' | 'out_of_stock';
            storeId: number;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PatchApiProductsByIdResponse = PatchApiProductsByIdResponses[keyof PatchApiProductsByIdResponses];
