// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteApiProductsById, deleteApiStoresById, getApiDashboardMetrics, getApiProducts, getApiProductsById, getApiStores, getApiStoresById, getHealth, type Options, patchApiProductsById, patchApiStoresById, postApiProducts, postApiStores } from '../sdk.gen';
import type { DeleteApiProductsByIdData, DeleteApiProductsByIdResponse, DeleteApiStoresByIdData, DeleteApiStoresByIdResponse, GetApiDashboardMetricsData, GetApiDashboardMetricsResponse, GetApiProductsByIdData, GetApiProductsByIdResponse, GetApiProductsData, GetApiProductsResponse, GetApiStoresByIdData, GetApiStoresByIdResponse, GetApiStoresData, GetApiStoresResponse, GetHealthData, PatchApiProductsByIdData, PatchApiProductsByIdResponse, PatchApiStoresByIdData, PatchApiStoresByIdResponse, PostApiProductsData, PostApiProductsResponse, PostApiStoresData, PostApiStoresResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getApiDashboardMetricsQueryKey = (options?: Options<GetApiDashboardMetricsData>) => createQueryKey('getApiDashboardMetrics', options);

export const getApiDashboardMetricsOptions = (options?: Options<GetApiDashboardMetricsData>) => queryOptions<GetApiDashboardMetricsResponse, DefaultError, GetApiDashboardMetricsResponse, ReturnType<typeof getApiDashboardMetricsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiDashboardMetrics({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiDashboardMetricsQueryKey(options)
});

export const getApiStoresQueryKey = (options?: Options<GetApiStoresData>) => createQueryKey('getApiStores', options);

export const getApiStoresOptions = (options?: Options<GetApiStoresData>) => queryOptions<GetApiStoresResponse, DefaultError, GetApiStoresResponse, ReturnType<typeof getApiStoresQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiStores({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiStoresQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getApiStoresInfiniteQueryKey = (options?: Options<GetApiStoresData>): QueryKey<Options<GetApiStoresData>> => createQueryKey('getApiStores', options, true);

export const getApiStoresInfiniteOptions = (options?: Options<GetApiStoresData>) => infiniteQueryOptions<GetApiStoresResponse, DefaultError, InfiniteData<GetApiStoresResponse>, QueryKey<Options<GetApiStoresData>>, number | Pick<QueryKey<Options<GetApiStoresData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiStoresData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiStores({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiStoresInfiniteQueryKey(options)
});

export const postApiStoresMutation = (options?: Partial<Options<PostApiStoresData>>): UseMutationOptions<PostApiStoresResponse, DefaultError, Options<PostApiStoresData>> => {
    const mutationOptions: UseMutationOptions<PostApiStoresResponse, DefaultError, Options<PostApiStoresData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiStores({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiStoresByIdMutation = (options?: Partial<Options<DeleteApiStoresByIdData>>): UseMutationOptions<DeleteApiStoresByIdResponse, DefaultError, Options<DeleteApiStoresByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteApiStoresByIdResponse, DefaultError, Options<DeleteApiStoresByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiStoresById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiStoresByIdQueryKey = (options: Options<GetApiStoresByIdData>) => createQueryKey('getApiStoresById', options);

export const getApiStoresByIdOptions = (options: Options<GetApiStoresByIdData>) => queryOptions<GetApiStoresByIdResponse, DefaultError, GetApiStoresByIdResponse, ReturnType<typeof getApiStoresByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiStoresById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiStoresByIdQueryKey(options)
});

export const patchApiStoresByIdMutation = (options?: Partial<Options<PatchApiStoresByIdData>>): UseMutationOptions<PatchApiStoresByIdResponse, DefaultError, Options<PatchApiStoresByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchApiStoresByIdResponse, DefaultError, Options<PatchApiStoresByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiStoresById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiProductsQueryKey = (options?: Options<GetApiProductsData>) => createQueryKey('getApiProducts', options);

export const getApiProductsOptions = (options?: Options<GetApiProductsData>) => queryOptions<GetApiProductsResponse, DefaultError, GetApiProductsResponse, ReturnType<typeof getApiProductsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiProducts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiProductsQueryKey(options)
});

export const getApiProductsInfiniteQueryKey = (options?: Options<GetApiProductsData>): QueryKey<Options<GetApiProductsData>> => createQueryKey('getApiProducts', options, true);

export const getApiProductsInfiniteOptions = (options?: Options<GetApiProductsData>) => infiniteQueryOptions<GetApiProductsResponse, DefaultError, InfiniteData<GetApiProductsResponse>, QueryKey<Options<GetApiProductsData>>, number | Pick<QueryKey<Options<GetApiProductsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiProductsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiProducts({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiProductsInfiniteQueryKey(options)
});

export const postApiProductsMutation = (options?: Partial<Options<PostApiProductsData>>): UseMutationOptions<PostApiProductsResponse, DefaultError, Options<PostApiProductsData>> => {
    const mutationOptions: UseMutationOptions<PostApiProductsResponse, DefaultError, Options<PostApiProductsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiProducts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiProductsByIdMutation = (options?: Partial<Options<DeleteApiProductsByIdData>>): UseMutationOptions<DeleteApiProductsByIdResponse, DefaultError, Options<DeleteApiProductsByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteApiProductsByIdResponse, DefaultError, Options<DeleteApiProductsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiProductsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiProductsByIdQueryKey = (options: Options<GetApiProductsByIdData>) => createQueryKey('getApiProductsById', options);

export const getApiProductsByIdOptions = (options: Options<GetApiProductsByIdData>) => queryOptions<GetApiProductsByIdResponse, DefaultError, GetApiProductsByIdResponse, ReturnType<typeof getApiProductsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiProductsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiProductsByIdQueryKey(options)
});

export const patchApiProductsByIdMutation = (options?: Partial<Options<PatchApiProductsByIdData>>): UseMutationOptions<PatchApiProductsByIdResponse, DefaultError, Options<PatchApiProductsByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchApiProductsByIdResponse, DefaultError, Options<PatchApiProductsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiProductsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
